"""empty message

Revision ID: 0ff6cd15b1cc
Revises: 045b63be8626
Create Date: 2021-09-06 17:43:10.169953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ff6cd15b1cc'
down_revision = '045b63be8626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infotag', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('infotag', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.drop_constraint('infotag_ibfk_1', 'infotag', type_='foreignkey')
    op.create_foreign_key(None, 'infotag', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'infotag', 'info', ['user_id'], ['id'])
    op.drop_column('infotag', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infotag', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'infotag', type_='foreignkey')
    op.drop_constraint(None, 'infotag', type_='foreignkey')
    op.create_foreign_key('infotag_ibfk_1', 'infotag', 'tag', ['id'], ['id'])
    op.drop_column('infotag', 'tag_id')
    op.drop_column('infotag', 'user_id')
    # ### end Alembic commands ###
