"""empty message

Revision ID: 90c80583ec07
Revises: 
Create Date: 2021-09-06 15:19:46.784278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c80583ec07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('info_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=75), nullable=True),
    sa.Column('phone_no', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('info_id')
    )
    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('infotag',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['info.info_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infotag')
    op.drop_table('tag')
    op.drop_table('info')
    # ### end Alembic commands ###
